apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: nginx-chaos
spec:
  appinfo:
    appns: 'default'
    applabel: 'app=nginx'
    appkind: 'deployment'
  # It can be active/stop
  engineState: 'active'
  #ex. values: ns1:name=percona,ns2:run=nginx
  auxiliaryAppInfo: ''
  chaosServiceAccount: hello-world-chaos-sa
  # It can be delete/retain
  jobCleanUpPolicy: 'delete'
  experiments:
    - name: hello-world-chaos
      spec:
        components:
          env:
            # set chaos duration (in sec) as desired
            - name: TOTAL_CHAOS_DURATION
              value: '300'

            # set chaos interval (in sec) as desired
            - name: CHAOS_INTERVAL
              value: '10'
            - name: CHAOS_INJECT_COMMAND
              value: 'md5sum /dev/zero'
            - name: CHAOS_KILL_COMMAND
              value: "kill $(find /proc -name exe -lname '*/md5sum' 2>&1 | grep -v 'Permission denied' | awk -F/ '{print $(NF-1)}')"
              