apiVersion: litmuchaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  name: generic 
  version: 0.1.0
  annotations:
    categories: generic
spec:
  displayName: generic chaos
  categoryDescription: >
    it execs inside target pods to run the chaos inject commands, waits for the chaos duration and reverts the chaos 
  experiments:
  - custom-pod-cpu-hog
  keywords: 
    - "pods" 
    - "kubernetes" 
    - "sample-category" 
    - "exec"
  maintainers: 
    - name: avinashjha 
      email: avinashjha@chaosnative.com
  minKubeVersion: 1.12.0 
  provider: 
    name: ChaosNative
  links: 
    - name: Documentation 
      url: https://docs.litmuschaos.io/docs/getstarted/ 
  icon:
    - url: 
      mediatype: ""
  chaosexpcrdlink: https://raw.githubusercontent.com/litmuschaos/chaos-charts/master/charts/generic/experiments.yaml